### ISSUE TITLE
examples/tcp-echo-server.rs Incorrect result

### ISSUE THREAD

**Issue by Clownsw** [bmatcuk/libuv-rs#4]
![捕获](https://user-images.githubusercontent.com/28394742/188281885-99090958-7dec-4748-a740-30465bd0ba64.PNG)

There seems to be something wrong with this result

**Comment by bmatcuk** [comment]
Hmm, I suspect this is just an issue with `nc` (or whatever program you used to connect to the server). How are you typing `F�rF`? Is that some sort of shell escape code? Perhaps nc is not sending it.

**Comment by Clownsw** [comment]
> 



> 嗯，我猜想是不是因为你的密码是这个`nc`服务器的程序`F�rF`？

I used telnet to connect my program and the above problem occurred, then I used netty to write a demo and found that libuv-rs would reply a lot of 00 bytes
